// lib/widgets/filters/panels/panel_vintage.dart
import 'dart:typed_data';
import 'dart:ui' as ui;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import '../presets.dart';
import 'panel_common.dart';
import '../engine/engine_vintage.dart' as eng;

/// 复古面板（20 个差异明显的预设；只在此处定义，不放 presets.dart）
class PanelVintage extends StatelessWidget {
  const PanelVintage({
    super.key,
    required this.img,
    required this.selectedId,
    required this.onPick,
  });

  final ui.Image img;
  final String? selectedId;
  final void Function(FilterPreset) onPick;

  @override
  Widget build(BuildContext context) {
    final items = _vintagePresets;
    return PanelGrid<FilterPreset>(
      img: img,
      items: items,
      selectedId: selectedId,
      idOf: (p) => p.id,
      onPick: onPick,
      // ✅ 缩略图跨 isolate：走复古引擎的 vintageApplyIsolate
      renderRgba: (base, w, h, p) async => compute<Map<String, dynamic>, Uint8List>(
        eng.vintageApplyIsolate,
        {'rgba': Uint8List.fromList(base), 'w': w, 'h': h, 'spec': p.toMap()},
      ),
    );
  }
}

// ======================= 20 个复古预设（差异明显，全中文） =======================
// 说明：每个预设只是“意图”，真正的复古味道由 engine_vintage 的基线融合来兜底；
//       这里通过色温/色调/分离色调/青橙力度/曲线/饱和等差异，做出风格区分。

const List<FilterPreset> _vintagePresets = [
  FilterPreset(
    id: '复古_茶褐',
    name: '茶褐',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    saturation: -0.14,
    vibrance: 0.10,
    temperature: 0.16,
    tint: -0.04,
    splitAmount: 0.18,
    splitBalance: 0.12,
    splitShadow: Color(0xFF2E5E55),
    splitHighlight: Color(0xFFD9A15A),
  ),
  FilterPreset(
    id: '复古_泛白',
    name: '泛白',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    matte: 0.18,
    contrast: -0.06,
    saturation: -0.18,
    vibrance: 0.06,
    temperature: 0.06,
  ),
  FilterPreset(
    id: '复古_冷蓝',
    name: '冷蓝',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    temperature: -0.18,
    tint: 0.02,
    saturation: -0.10,
    splitAmount: 0.16,
    splitBalance: -0.08,
    splitShadow: Color(0xFF2B5F7A),
    splitHighlight: Color(0xFFE0C49A),
  ),
  FilterPreset(
    id: '复古_旧纸',
    name: '旧纸',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    temperature: 0.22,
    tint: -0.06,
    saturation: -0.16,
    vibrance: 0.10,
    splitAmount: 0.20,
    splitBalance: 0.10,
    splitShadow: Color(0xFF2F5E3F),
    splitHighlight: Color(0xFFE4C07A),
  ),
  FilterPreset(
    id: '复古_红铜',
    name: '红铜',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    temperature: 0.18,
    tint: 0.04,
    saturation: -0.08,
    splitAmount: 0.22,
    splitBalance: 0.18,
    splitShadow: Color(0xFF3A4F56),
    splitHighlight: Color(0xFFE49B6A),
  ),
  FilterPreset(
    id: '复古_青铜',
    name: '青铜',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    temperature: 0.06,
    tint: -0.08,
    saturation: -0.12,
    splitAmount: 0.20,
    splitBalance: 0.00,
    splitShadow: Color(0xFF2B6B5E),
    splitHighlight: Color(0xFFC9A56A),
  ),
  FilterPreset(
    id: '复古_绿味',
    name: '绿味',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    saturation: -0.10,
    tint: -0.10,
    vibrance: 0.10,
    splitAmount: 0.16,
    splitBalance: -0.02,
    splitShadow: Color(0xFF2C6B4A),
    splitHighlight: Color(0xFFE3C18A),
  ),
  FilterPreset(
    id: '复古_冷柔',
    name: '冷柔',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    contrast: -0.04,
    temperature: -0.12,
    saturation: -0.12,
    vibrance: 0.12,
    splitAmount: 0.14,
    splitBalance: -0.04,
    splitShadow: Color(0xFF2E6072),
    splitHighlight: Color(0xFFE6C9A2),
  ),
  FilterPreset(
    id: '复古_粉旧',
    name: '粉旧',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    saturation: -0.08,
    vibrance: 0.12,
    temperature: 0.08,
    tint: 0.06,
    duoA: Color(0xFF3A3A3A),
    duoB: Color(0xFFE8B7C0),
    duoAmount: 0.18,
  ),
  FilterPreset(
    id: '复古_奶油',
    name: '奶油',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    matte: 0.16,
    contrast: -0.02,
    saturation: -0.12,
    temperature: 0.10,
    vibrance: 0.08,
  ),
  FilterPreset(
    id: '复古_冷绿',
    name: '冷绿',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    temperature: -0.10,
    tint: -0.08,
    saturation: -0.10,
    splitAmount: 0.18,
    splitBalance: -0.06,
    splitShadow: Color(0xFF2D6B63),
    splitHighlight: Color(0xFFE2C6A0),
  ),
  FilterPreset(
    id: '复古_茶影',
    name: '茶影',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    saturation: -0.16,
    temperature: 0.20,
    splitAmount: 0.22,
    splitBalance: 0.12,
    splitShadow: Color(0xFF2F5E3F),
    splitHighlight: Color(0xFFD6A06A),
  ),
  FilterPreset(
    id: '复古_日晒',
    name: '日晒',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    exposureEv: 0.12,
    contrast: -0.06,
    saturation: -0.10,
    temperature: 0.16,
    vibrance: 0.10,
  ),
  FilterPreset(
    id: '复古_蓝青',
    name: '蓝青',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    temperature: -0.16,
    tint: -0.02,
    saturation: -0.10,
    splitAmount: 0.16,
    splitBalance: -0.10,
    splitShadow: Color(0xFF1F6C7A),
    splitHighlight: Color(0xFFE7C89A),
  ),
  FilterPreset(
    id: '复古_老底片',
    name: '老底片',
    cat: FilterCategory.vintage,
    curve: CurveType.film,
    matte: 0.10,
    contrast: 0.06,
    saturation: -0.12,
    hueShift: -6.0,
  ),
  FilterPreset(
    id: '复古_米黄',
    name: '米黄',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    saturation: -0.10,
    temperature: 0.22,
    tint: -0.06,
    vibrance: 0.08,
  ),
  FilterPreset(
    id: '复古_灰雾',
    name: '灰雾',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    matte: 0.20,
    contrast: -0.10,
    saturation: -0.18,
    vibrance: 0.06,
    temperature: 0.04,
  ),
  FilterPreset(
    id: '复古_青灰',
    name: '青灰',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    temperature: -0.08,
    tint: -0.06,
    saturation: -0.14,
    splitAmount: 0.14,
    splitBalance: -0.04,
    splitShadow: Color(0xFF2B6B5E),
    splitHighlight: Color(0xFFC9B38A),
  ),
  FilterPreset(
    id: '复古_琥珀',
    name: '琥珀',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    saturation: -0.10,
    vibrance: 0.10,
    temperature: 0.24,
    splitAmount: 0.20,
    splitBalance: 0.16,
    splitShadow: Color(0xFF3B5750),
    splitHighlight: Color(0xFFE0A563),
  ),
  FilterPreset(
    id: '复古_旧夜',
    name: '旧夜',
    cat: FilterCategory.vintage,
    curve: CurveType.matte,
    exposureEv: -0.10,
    temperature: -0.10,
    saturation: -0.14,
    vibrance: 0.12,
    splitAmount: 0.18,
    splitBalance: -0.06,
    splitShadow: Color(0xFF28506A),
    splitHighlight: Color(0xFFE0BC8A),
  ),
];
